# Generated by Django 4.0.5 on 2022-06-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0003_alter_userprofiles_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='profile_pic',
            field=models.ImageField(blank=True, default='nopic', upload_to='profileimage'),
            preserve_default=False,
        ),
    ]
