# Generated by Django 4.0.5 on 2022-06-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0005_alter_userprofiles_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='Activation_Status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
