# Generated by Django 4.0.5 on 2022-07-03 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0006_alter_userprofiles_activation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=20, unique=True)),
                ('createdByUsername', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('Details', models.TextField(blank=True, max_length=200, null=True)),
                ('target', models.BigIntegerField()),
                ('startTime', models.DateTimeField(default=datetime.date(2022, 7, 3))),
                ('endTime', models.DateTimeField()),
                ('projectRating', models.IntegerField(default=100)),
                ('donations', models.BigIntegerField(default=0)),
            ],
        ),
    ]
