# Generated by Django 4.0.5 on 2022-07-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0007_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projectName',
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
