# Generated by Django 4.0.5 on 2022-07-03 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0008_remove_projects_projectname_alter_projects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 16, 51, 34, 367670, tzinfo=utc)),
        ),
    ]
