# Generated by Django 4.0.5 on 2022-07-03 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0009_alter_projects_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='startTime',
            field=models.DateTimeField(default=datetime.date(2022, 7, 3)),
        ),
    ]
