# Generated by Django 4.0.5 on 2022-07-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0012_alter_projects_endtime_alter_projects_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.ImageField(upload_to='profileimage')),
                ('createdByProject', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('ProjectTitle', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
