# Generated by Django 4.0.5 on 2022-07-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0013_images_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ProjectTitle',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
