# Generated by Django 4.0.5 on 2022-07-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0017_userprofiles_totaldonated_alter_projects_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='donations',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='donations',
            field=models.BigIntegerField(default=0),
        ),
    ]
